### ISSUE TITLE
huh

### ISSUE THREAD

**Issue by Cowthecow94** [Cowthecow94/Cowthecow94.github.io#2]
@rasafhw umm 
![Screenshot 2024-11-08 10 08 43 PM](https://github.com/user-attachments/assets/3fc10fdb-6b78-4330-8239-3d4d07735a0f)
happens when opening nzp.html

**Comment by Cowthecow94** [comment]
wait now it doesn't

**Comment by rasafhw** [comment]
Wait did you change anything

**Comment by rasafhw** [comment]
Wait did you change anything

**Comment by Cowthecow94** [comment]
no and also my extension (Ublock origin) is blocking the embed because it is likely to be malware or something (it says "This page has been blocked by an extension" when I hover over the embed) and after I turn off the extension it says it refused to connect.

**Comment by Cowthecow94** [comment]
(whoops I accidently closed the issue)
