### ISSUE TITLE
Need to embed C# file into the test embed

### ISSUE THREAD

**Issue by rasafhw** [Cowthecow94/Cowthecow94.github.io#8]
Idk how and I want to have a console conneted to the embed itself so I can run code in the embed @Cowthecow94

**Comment by Cowthecow94** [comment]
Ummm... console for what though?

**Comment by Cowthecow94** [comment]
You need to use an embed tag and link it to the console, not a textarea.

**Comment by rasafhw** [comment]
I had an AI do that it's not my fault

**Comment by Cowthecow94** [comment]
Lol ok
